

CREATE OR REPLACE WAREHOUSE IF NOT EXISTS TEST_WH
WITH
  WAREHOUSE_SIZE = 'LARGE'
  AUTO_SUSPEND = 60
  AUTO_RESUME = true
  COMMENT = 'this is a test wh';



CREATE DATABASE IF NOT EXISTS TEST_DB
 COMMENT = '';



CREATE ROLE IF NOT EXISTS TEST_ROLE
COMMENT = 'this is a test role';



CREATE SCHEMA IF NOT EXISTS TEST_DB.TEST_SCHEMA
COMMENT = 'this is a test schema';



CREATE USER IF NOT EXISTS TEST_USER
  PASSWORD = 'TEST_USER'
  DISPLAY_NAME = 'TEST_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = TEST_WH
  DEFAULT_NAMESPACE = TEST_DB.TEST_SCHEMA
  DEFAULT_ROLE = TEST_ROLE;

