USE ROLE ACCOUNTADMIN;


CREATE ROLE IF NOT EXISTS TEST_ROLE
COMMENT = 'this is a test role to show json structure';

GRANT ROLE TEST_ROLE TO ROLE SYSADMIN;

USE ROLE SYSADMIN;


CREATE WAREHOUSE IF NOT EXISTS TEST_WH
WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = true
  COMMENT = 'this is a test to show json structure.';

USE ROLE SYSADMIN;


CREATE DATABASE IF NOT EXISTS TEST_DB
 COMMENT = 'this is a test db to show json structure';

USE ROLE SYSADMIN;


CREATE SCHEMA IF NOT EXISTS TEST_DB.TEST_SCHEMA
COMMENT = 'this is a test schema to show json structure';

USE ROLE ACCOUNTADMIN;


CREATE USER IF NOT EXISTS TEST_USER
  PASSWORD = 'TEST_USER'
  DISPLAY_NAME = 'TEST_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = TEST_WH
  DEFAULT_NAMESPACE = TEST_DB.TEST_SCHEMA
  DEFAULT_ROLE = TEST_ROLE;

USE ROLE SYSADMIN;

GRANT USAGE ON DATABASE TEST_DB TO ROLE PUBLIC;

GRANT USAGE ON SCHEMA TEST_DB.TEST_SCHEMA TO ROLE PUBLIC;

GRANT USAGE ON DATABASE TEST_DB TO ROLE TEST_ROLE;

GRANT ALL ON SCHEMA TEST_DB.TEST_SCHEMA TO ROLE TEST_ROLE;

USE ROLE SECURITYADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TEST_DB.TEST_SCHEMA TO ROLE PUBLIC;
GRANT ALL ON FUTURE TABLES IN SCHEMA TEST_DB.TEST_SCHEMA TO ROLE TEST_ROLE;

USE ROLE SYSADMIN;


CREATE TABLE IF NOT EXISTS TEST_DB.TEST_SCHEMA.TEST_TABLE (

TEST_COLUMN NUMBER,
TEST_COLUMN_STR VARCHAR);

