USE ROLE SYSADMIN;

create pipe IF NOT EXISTS TEST_DB.TEST_SCHEMA.TEST_PIPE auto_ingest=TRUE as
 copy into TEST_DB.TEST_SCHEMA.TEST_TABLE (TEST_COLUMN)
 from (
   SELECT * FROM @TEST_DB.TEST_SCHEMA.TEST_STAGE)
 file_format = (type = 'PARQUET');