

CREATE SCHEMA IF NOT EXISTS RAW_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS RAW_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS RAW_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS RAW_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS REFINED_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS REFINED_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS REFINED_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS REFINED_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS ANALYTICS_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS ANALYTICS_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS ANALYTICS_LAYER
    COMMENT = '{comment}';

CREATE SCHEMA IF NOT EXISTS ANALYTICS_LAYER
    COMMENT = '{comment}';