

CREATE USER IF NOT EXISTS DEV_USER
  PASSWORD = 'DEV_USER'
  DISPLAY_NAME = 'DEV_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = DEV_WH
  DEFAULT_NAMESPACE = DEV_DB.RAW_LAYER
  DEFAULT_ROLE = DEV_ROLE;


CREATE USER IF NOT EXISTS QA_USER
  PASSWORD = 'QA_USER'
  DISPLAY_NAME = 'QA_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = QA_WH
  DEFAULT_NAMESPACE = QA_DB.RAW_LAYER
  DEFAULT_ROLE = QA_ROLE;


CREATE USER IF NOT EXISTS STG_USER
  PASSWORD = 'STG_USER'
  DISPLAY_NAME = 'STG_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = STG_WH
  DEFAULT_NAMESPACE = STG_DB.RAW_LAYER
  DEFAULT_ROLE = STG_ROLE;


CREATE USER IF NOT EXISTS PROD_USER
  PASSWORD = 'PROD_USER'
  DISPLAY_NAME = 'PROD_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = PROD_WH
  DEFAULT_NAMESPACE = PROD_DB.RAW_LAYER
  DEFAULT_ROLE = PROD_ROLE;


CREATE USER IF NOT EXISTS ANALYTICS_USER
  PASSWORD = 'ANALYTICS_USER'
  DISPLAY_NAME = 'ANALYTICS_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = ANALYTICS_WH
  DEFAULT_NAMESPACE = PROD_DB.REFINED_LAYER
  DEFAULT_ROLE = ANALYTICS_ROLE;


CREATE USER IF NOT EXISTS TABLEAU_USER
  PASSWORD = 'TABLEAU_USER'
  DISPLAY_NAME = 'TABLEAU_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = ANALYTICS_WH
  DEFAULT_NAMESPACE = PROD_DB.REFINED_LAYER
  DEFAULT_ROLE = ANALYTICS_ROLE;


CREATE USER IF NOT EXISTS TMO_USER
  PASSWORD = 'TMO_USER'
  DISPLAY_NAME = 'TMO_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = TMO_WH
  DEFAULT_NAMESPACE = PROD_DB.REFINED_LAYER
  DEFAULT_ROLE = TMO_ROLE;
