

CREATE USER IF NOT EXISTS TEST_USER
  PASSWORD = 'TEST_USER'
  DISPLAY_NAME = 'TEST_USER'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_WAREHOUSE = TEST_WH
  DEFAULT_NAMESPACE = TEST_DB.TEST_SCHEMA
  DEFAULT_ROLE = TEST_ROLE;
